version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - plantuml
  jobs:
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry
    post_create_environment:
      # TODO (ST 18-03-2024): Await published uniform approach to resolving
      # build errors resulting from poetry versions 1.8.0 and higher
      - pip install poetry
    post_install:
      # Install dependencies with 'docs' dependency group. If you do not have docs group, please omit it
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --only docs

sphinx:
  configuration: docs/src/conf.py
