{{ $localchart := . }}

{{- range $key, $deviceserver := .Values.deviceServers }}

{{ if $deviceserver.enabled }}

{{- $filedeviceserver := tpl ($.Files.Get $deviceserver.file) $ | fromYaml }}

{{- $_ := set $filedeviceserver "instances" $localchart.Values.global.dishes }}
{{- $context := dict "name" $key "deviceserver" $filedeviceserver "image" $deviceserver.image "local" $localchart }}

{{ template "ska-tango-util.multidevice-config.tpl" $context }}
{{ template "ska-tango-util.multidevice-sacc-role.tpl" $context }}
{{ template "ska-tango-util.multidevice-job.tpl" $context }}
{{ template "ska-tango-util.multidevice-svc.tpl" $context }} 

{{- end }} # if enabled

{{- end }} # deviceservers

