"""File for defining constants."""

DEFAULT_DISH_ID = "SKA001"
DEFAULT_DISH_MANAGER_TRL = "mid-dish/dish-manager/SKA001"
DEFAULT_DS_MANAGER_TRL = "mid-dish/ds-manager/SKA001"
DEFAULT_SPFC_TRL = "mid-dish/simulator-spfc/SKA001"
DEFAULT_SPFRX_TRL = "mid-dish/simulator-spfrx/SKA001"
BAND_POINTING_MODEL_PARAMS_LENGTH = 18
DSC_MAX_POWER_LIMIT_KW = 20.0
DSC_MIN_POWER_LIMIT_KW = 10.0
MEAN_WIND_SPEED_THRESHOLD_MS = 11.1  # m/s
WIND_GUST_THRESHOLD_MS = 16.9  # m/s
