"""File for defining constants."""

DEFAULT_DISH_ID = "SKA001"
DEFAULT_DISH_MANAGER_TRL = "mid-dish/dish-manager/SKA001"
DEFAULT_DS_MANAGER_TRL = "mid-dish/ds-manager/SKA001"
DEFAULT_SPFC_TRL = "mid-dish/simulator-spfc/SKA001"
DEFAULT_SPFRX_TRL = "mid-dish/simulator-spfrx/SKA001"
DEFAULT_WMS_TRL = "ska-mid/weather-monitoring/1"
BAND_POINTING_MODEL_PARAMS_LENGTH = 18
DSC_MAX_POWER_LIMIT_KW = 20.0
DSC_MIN_POWER_LIMIT_KW = 10.0
MEAN_WIND_SPEED_THRESHOLD_MPS = 11.1
WIND_GUST_THRESHOLD_MPS = 16.9
