"""File for defining constants."""

DEFAULT_DISH_ID = "SKA001"
DEFAULT_DISH_MANAGER_TRL = "mid-dish/dish-manager/SKA001"
DEFAULT_DS_MANAGER_TRL = "mid-dish/ds-manager/SKA001"
DEFAULT_SPFC_TRL = "mid-dish/simulator-spfc/SKA001"
DEFAULT_SPFRX_TRL = "mid-dish/simulator-spfrx/SKA001"
DEFAULT_WMS_TRL = "ska-mid/weather-monitoring/1"
DEFAULT_WATCHDOG_TIMEOUT = 0.0
MAINTENANCE_MODE_ACTIVE_PROPERTY = "MaintenanceModeActive"
BAND_POINTING_MODEL_PARAMS_LENGTH = 18
DSC_MAX_POWER_LIMIT_KW = 20.0
DSC_MIN_POWER_LIMIT_KW = 10.0
DEFAULT_MAINTENANCE_MODE = "MAINTENANCE"
MEAN_WIND_SPEED_THRESHOLD_MPS = 11.1
WIND_GUST_THRESHOLD_MPS = 16.9

STOW_ELEVATION_DEGREES = 90.2  # degrees
STOW_SPEED_DEGREES_PER_SECOND = 1.0  # degrees per second
