enabled: true

system: SW-infrastructure
subsystem: ska-dish-lmc
telescope: SKA-mid

labels:
  app: ska-mid-dish-simulators

legacy_compatibility: true

global:
  minikube: false
  tango_host: databaseds-tango-base-test:10000
  retry:
    - "--tries=10"

  # List instances to be deployed. e.g. 001 means
  # 1 SPF and SPFRx device per dish. Values follow the
  # mnenomic Dish ID defined in ADR-32 001 >= nnn <= 133
  dishes: ["001"]

dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.11
    pullPolicy: IfNotPresent

dishsimulators:
  image:
    registry: artefact.skao.int
    image: ska-mid-dish-simulators
    tag: 1.2.0
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

deviceServers:
  spfdevice:
    file: "data/spf_device.yaml"
    enabled: false
  spfrxdevice:
    file: "data/spfrx_device.yaml"
    enabled: false
