---
apiVersion: v1
kind: Pod
metadata:
  name: sandbox
  namespace: ska-mid-dish-manager
spec:
  containers:
    - name: sandbox-pod
      image: artefact.skao.int/ska-tango-images-tango-itango:9.3.4
      imagePullPolicy: IfNotPresent
      stdin: true
      stdinOnce: true
      tty: true
      workingDir: "/home/tango"
      env:
        - name: TANGO_HOST
          value: databaseds-tango-base-test:10000
      ports:
        - containerPort: 22
          name: ssh
          protocol: TCP
      resources:
        requests:
          cpu: 1000m
          memory: 256Mi
        limits:
          cpu: 1500m
          memory: 512Mi
