{{ if .Values.vnc.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "ska-tango-base.name" . }}-{{ .Values.vnc.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: {{ .Values.vnc.component }}
    function: {{ .Values.vnc.function }}
    domain: {{ .Values.vnc.domain }}
    intent: {{ .Values.vnc.intent }}
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
{{ if or (.Values.global.annotations) (.Values.annotations) }}
  annotations:
{{ toYaml (coalesce .Values.global.annotations .Values.annotations) | indent 4 }}
{{ end }}
spec:
  type: NodePort
  ports:
  - name: vncport
    port: 5920
    protocol: TCP
{{ if .Values.vnc.nodeport_enabled }}
    nodePort: {{ .Values.vnc.nodeport_vnc }}
{{end}}
  - name: novncport
    port: 6081
    protocol: TCP
{{ if .Values.vnc.nodeport_enabled }}
    nodePort: {{ .Values.vnc.nodeport_novnc }}
{{end}}
  selector:
    component: {{ .Values.vnc.component }}
    function: {{ .Values.vnc.function }}
    domain: {{ .Values.vnc.domain }}
    intent: {{ .Values.vnc.intent }}
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "ska-tango-base.name" . }}-{{ .Values.vnc.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: {{ .Values.vnc.component }}
    function: {{ .Values.vnc.function }}
    domain: {{ .Values.vnc.domain }}
    intent: {{ .Values.vnc.intent }}
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
{{ if or (.Values.global.annotations) (.Values.annotations) }}
  annotations:
{{ toYaml (coalesce .Values.global.annotations .Values.annotations) | indent 4 }}
{{ end }}
spec:
  selector:
    matchLabels:
      component: {{ .Values.vnc.component }}
      function: {{ .Values.vnc.function }}
      domain: {{ .Values.vnc.domain }}
      intent: {{ .Values.vnc.intent }}
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 6 }}
  serviceName: {{ template "ska-tango-base.name" . }}-{{ .Values.vnc.component }}
  replicas:  {{ .Values.vnc.replicas }}
  template:
    metadata:
      labels:
        component: {{ .Values.vnc.component }}
        function: {{ .Values.vnc.function }}
        domain: {{ .Values.vnc.domain }}
        intent: {{ .Values.vnc.intent }}
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 8 }}
{{ if or (.Values.global.annotations) (.Values.annotations) }}
      annotations:
{{ toYaml (coalesce .Values.global.annotations .Values.annotations) | indent 8 }}
{{ end }}
    spec:
      containers:
      - name: vnc
        image: "{{ .Values.vnc.image.registry }}/{{ .Values.vnc.image.image }}:{{ .Values.vnc.image.tag }}"
        imagePullPolicy: {{ .Values.vnc.image.pullPolicy }}
        ports:
        - name: vncport
          containerPort: 5920
        - name: novncport
          containerPort: 6081
        env:
        - name: KUBE_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: HELM_RELEASE
          value: {{ .Release.Name }}
        - name: TANGO_HOST
          value: "{{ .Values.global.tango_host }}"
        resources:
{{ toYaml .Values.vnc.resources | indent 10 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{ end }}