global:
  minikube: true
  operator: false
  dishes: ["001","111"]

ska-mid-dish-ds-manager:
  enabled: true

ska-tango-base:
  enabled: true

ska-mid-dish-simulators:
  enabled: true
  deviceServers:
    spfdevice:
      enabled: true
    spfrxdevice:
      enabled: true
  dsOpcuaSimulator:
    enabled: true

dishmanager:
  windLimits:
    # Wind speed in m/s
    MeanWindSpeedThreshold: "10.0"
    # Wind gust in m/s
    WindGustThreshold: "15.0"

ska-mid-wms:
  enabled: true
  ska-tango-base:
    enabled: false
    itango:
      enabled: false
  deviceServers:
    wms:
      enabled: true
  wmsConfig:
    Host: ["wms-sim-3"] # hostname of the modbus devices
    Port: ["1502"] # port of the modbus devices (default sim port is 1502)
    # List of WMS instances to deploy (also corresponds to simulator IDs)
    # Each item in this list will create a device server instance.
    instances: ["3"]
  simulator:
    enabled: True
