global:
  minikube: true
  operator: true
  dishes: ["001", "MKT111"]
  station_ids: ["s1"]

ska-tango-base:
  enabled: true

ska-mid-dish-ds-manager:
  enabled: true

ska-mid-dish-simulators:
  enabled: true
  deviceServers:
    spfdevice:
      enabled: true
    spfrxdevice:
      enabled: true
  dsOpcuaSimulator:
    enabled: true

ska-mid-wms:
  enabled: false

# Meerkat tango device
ska-mid-meerkat-wms-tango-device:
  enabled: true
  deviceServers:
    meerkatwms:
      enabled: true
      file: "data/weather_tango_device.yaml"

  weathertangodevice:
    image:
      registry: artefact.skao.int
      image: ska-mid-meerkat-lmc
      tag: 0.1.0
      pullPolicy: IfNotPresent

  dsconfig:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.8.5
# Meerkat weather simulator
ska-mid-meerkat-wms-simulator:
  enabled: true
  weatherstation:
    enabled: true
    image:
      registry: artefact.skao.int
      image: ska-mid-meerkat-lmc-katcp-sims
      tag: 0.1.0
      pullPolicy: IfNotPresent

ska-mid-dish-b5dc-proxy:
  enabled: true

dishmanager:
  wms:
    monitoring: true
    station_ids: ["1"]
    device_family: "mk-weather-monitoring"
    station_ids: ["s1"]
  b5dcproxy:
    monitoring: true
