global:
  minikube: true
  operator: true
  dishes: ["001"]

ska-mid-dish-ds-manager:
  enabled: true

ska-tango-base:
  enabled: true

ska-mid-dish-simulators:
  enabled: true
  deviceServers:
    spfdevice:
      enabled: true
    spfrxdevice:
      enabled: true
  dsOpcuaSimulator:
    enabled: true

dishmanager:
  windLimits:
    # Wind speed in m/s
    MeanWindSpeedThreshold: "10.0"
    # Wind gust in m/s
    WindGustThreshold: "15.0"

ska-mid-wms:
  enabled: true
  ska-tango-base:
    enabled: false
    itango:
      enabled: false
  deviceServers:
    wms:
      enabled: true
      station_ids: ["1"]
      modbus_server_hostnames: ["wms-sim-1"]
      modbus_server_ports: ["1502"]
  simulator:
    enabled: True
