# deploy dish-manager with only ds-manager, spfrx and spf sim with default instance 001
global:
  minikube: true
  operator: true

ska-mid-dish-ds-manager:
  enabled: true

ska-tango-base:
  enabled: true

ska-mid-dish-simulators:
  enabled: true
  dishsimulators:
    image:
      registry: registry.gitlab.com/ska-telescope/mid-dish/ska-mid-dish-simulators
      tag: 5.11.0-dev.c58f7e83a
  deviceServers:
    spfdevice:
      enabled: true
    spfrxdevice:
      enabled: true
  dsOpcuaSimulator:
    enabled: true

