enabled: true

ska-mid-dish-simulators:
  enabled: false

ska-mid-dish-ds-manager:
  enabled: false
  dishstructuremanager:
    image:
      registry: registry.gitlab.com/ska-telescope/ska-mid-dish-ds-manager
      tag: 6.4.1-dev.cd05ee2ec

system: SW-infrastructure
subsystem: ska-dish-lmc
telescope: SKA-mid

labels:
  app: ska-mid-dish-manager

ska-tango-base:
  enabled: false

global:
  minikube: false
  operator: false
  tango_host: databaseds-tango-base-test:10000
  retry:
  - "--tries=10"

  ## Order of instances resolution ##
  # .Values.global.dishes
  # .Values.deviceServers.<device>.instances
  # File, data/<device>.yaml, instances

  # List the dishes, if set, then this list will be
  # applied to instances of > deviceServers.dishmanager
  # Values follow the sequence in the mnenomic Dish ID
  # defined in ADR-32 i.e. SKA[nnn] where nnn starts
  # from 001 to 133
  dish_devices: ["dish-manager"]
  dishes: ["001"]


dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.11
    pullPolicy: IfNotPresent

dishmanager:
  image:
    registry: artefact.skao.int
    image: mid-dish/ska-mid-dish-manager
    tag: 8.4.7
    pullPolicy: IfNotPresent

  # Setting fqdn assumes you are only deploying one Dish Manager
  # with custom sub devices addresses
  # Otherwise device names will follow "mid-dish/<family_name>/ska0<N>" for N dishes
  spf:
    ignored: False
    fqdn: ""
    domain_name: "mid-dish"
    family_name: "simulator-spfc"

  ds:
    fqdn: ""
    domain_name: "mid-dish"
    family_name: "ds-manager"

  spfrx:
    ignored: False
    fqdn: ""
    domain_name: "mid-dish"
    family_name: "simulator-spfrx"

  wms:
    # device server instances (empty list disables monitoring on WMS devices)
    station_ids: []
    # Wind speed in m/s
    MeanWindSpeedThreshold: "11.1"
    # Wind gust in m/s
    WindGustThreshold: "16.9"

  watchdog:
    timeout_seconds: "0.0"  # Default is 0.0 (<= 0 means watchdog timer is disabled)

  actions:
    timeout_seconds: "120.0"  # Default is 120s (<= 0 means the actions will not wait for anything)

dev_pod:
  enabled: false

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 375Mi

deviceServers:
  dishmanager:
    file: "data/dish_manager.yaml"
    enabled: true

ska-mid-wms:
  enabled: false
  ska-tango-base:
    enabled: false
    itango:
      enabled: false
  deviceServers:
    wms:
      enabled: true
      station_ids: ["1"]
      modbus_server_hostnames: ["wms-sim-1"]
      modbus_server_ports: ["1502"]
  simulator:
    enabled: True
