enabled: true

ska-mid-dish-simulators:
  enabled: false

system: SW-infrastructure
subsystem: ska-dish-lmc
telescope: SKA-mid

labels:
  app: ska-mid-dish-manager

global:
  minikube: false
  tango_host: databaseds-tango-base-test:10000
  retry:
  - "--tries=10"

  ## Order of instances resolution ##
  # .Values.global.dishes
  # .Values.deviceServers.<device>.instances
  # File, data/<device>.yaml, instances

  # List the dishes, if set, then this list will be applied to instances of:
  # deviceServers.dishmaster
  dish_devices: ["dish-manager"]
  dishes: ["01"]


dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.1
    pullPolicy: IfNotPresent

dishmanager:
  image:
    registry: artefact.skao.int
    image: ska-mid-dish-manager
    tag: 1.6.0
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

deviceServers:
  dishmanager:
    file: "data/dish_manager.yaml"
    enabled: true
  dsdevice:
    file: "data/ds_device.yaml"
    enabled: false
