enabled: true

ska-mid-dish-simulators:
  enabled: false

ska-mid-dish-ds-manager:
  enabled: false
  dishstructuremanager:
    image:
      registry: registry.gitlab.com/ska-telescope/ska-mid-dish-ds-manager
      image: ska-mid-dish-ds-manager
      tag: 3.1.0-dev.c6e49d66e
      pullPolicy: IfNotPresent

system: SW-infrastructure
subsystem: ska-dish-lmc
telescope: SKA-mid

labels:
  app: ska-mid-dish-manager

ska-tango-base:
  enabled: false

global:
  minikube: false
  operator: false
  tango_host: databaseds-tango-base-test:10000
  retry:
  - "--tries=10"

  ## Order of instances resolution ##
  # .Values.global.dishes
  # .Values.deviceServers.<device>.instances
  # File, data/<device>.yaml, instances

  # List the dishes, if set, then this list will be
  # applied to instances of > deviceServers.dishmanager
  # Values follow the sequence in the mnenomic Dish ID
  # defined in ADR-32 i.e. SKA[nnn] where nnn starts
  # from 001 to 133
  dish_devices: ["dish-manager"]
  dishes: ["001"]


dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.11
    pullPolicy: IfNotPresent

dishmanager:
  image:
    registry: artefact.skao.int
    image: ska-mid-dish-manager
    tag: 6.0.1
    pullPolicy: IfNotPresent

  # Setting fqdn assumes you are only deploying one Dish Manager
  # with custom sub devices addresses
  # Otherwise device names will follow "mid-dish/<family_name>/ska0<N>" for N dishes
  spf:
    ignored: False
    fqdn: ""
    domain_name: "mid-dish"
    family_name: "simulator-spfc"

  ds:
    fqdn: ""
    domain_name: "mid-dish"
    family_name: "ds-manager"

  spfrx:
    ignored: False
    fqdn: ""
    domain_name: "mid-dish"
    family_name: "simulator-spfrx"

dev_pod:
  enabled: false

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

deviceServers:
  dishmanager:
    file: "data/dish_manager.yaml"
    enabled: true
