{{ if .Values.dummy_device.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dummy-device-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dummy-device
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: dummy-device-{{ .Release.Name }}
  replicas: {{ .Values.dummy_device.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dummy-device
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: dummy-device
          image: "{{ .Values.dishmanager.image.registry }}/{{ .Values.dishmanager.image.image }}:{{ .Values.dishmanager.image.tag }}"
          imagePullPolicy: {{ .Values.dishmanager.image.pullPolicy }}
          command:
            - /usr/local/bin/wait-for-it.sh
            - {{ .Values.global.tango_host }}
            - --timeout=60
            - --
            - /usr/bin/python3
            - /usr/local/bin/DummyDevice
            - test
          env:
          - name: TANGO_HOST
            value: {{ .Values.global.tango_host}}
{{ end }}
